# Generated by Django 4.2.4 on 2023-08-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('sky_condition', models.CharField(max_length=200)),
                ('temperature', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('pressure', models.IntegerField()),
                ('humidity', models.FloatField()),
            ],
        ),
    ]
