# Generated by Django 4.2.4 on 2023-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='source',
            field=models.CharField(choices=[('openweather', 'OpenWeather'), ('weatherapi', 'WeatherAPI')],
                                   default='default', max_length=20),
            preserve_default=False,
        ),
    ]
