# Generated by Django 4.2.4 on 2023-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0002_weather_date_weather_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='image',
            field=models.CharField(default='static/icons/cloud.png', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='source',
            field=models.CharField(
                choices=[('openweather', 'OpenWeather'), ('weatherapi', 'WeatherAPI'), ('average', 'Average')],
                max_length=20),
        ),
    ]
