# Generated by Django 4.2.4 on 2023-08-21 22:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ('weather', '0004_alter_weather_humidity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='weather',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
